name: api-server-deploy
on: 
  push:
    branches: [ master ]
jobs:
  api-server-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: remove
        run: rm -rf /home/opc/api-server/*

      - name: cp
        run: cp -r ./* /home/opc/api-server/

      - name: yarn install
        run: yarn install
        working-directory: /home/opc/api-server/
