name: api-server-deploy
on: 
  push:
    branches: [ master ]
jobs:
  api-server-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      # - name: test2
      #   run: find /home/opc/api-server -name node_modules -prune -o -delete
      
      # - name: test
      #   run: ls | find . -name node_modules -prune -o -print
      #   working-directory: /home/opc/api-server/

      - name: cp
        run: cp -r ./* /home/opc/api-server/

      - name: yarn install
        run: yarn install
        working-directory: /home/opc/api-server/

      - name: yarn reload
        run: yarn reload
        working-directory: /home/opc/api-server/
