name: api-server-deploy
on: 
  push:
    branches: [ master ]
jobs:
  api-server-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: remove
        run: find /home/opc/api-server -mindepth 1 -maxdepth 1 ! -name node_modules | xargs rm -rf

      - name: cp
        run: cp -r ./* /home/opc/api-server/

      - name: cp-admin
        run: cp -r /home/opc/admin-password.dat /home/opc/api-server/

      - name: yarn install
        run: yarn install
        working-directory: /home/opc/api-server/

      - name: yarn reload
        run: yarn reload
        working-directory: /home/opc/api-server/
