name: api-server-deploy
on: 
  push:
    branches: [ master ]
jobs:
  api-server-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
        rm -rf /home/opc/api-server/*
        cp -r ./* /home/opc/api-server/
        cd /home/opc/api-server/
        yarn install